<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert(
            array('id' => '1','category_id' => NULL,'name' => 'Document translation spanish to english [Birth Marriage Degree]','language' => 'Spanish to English','slug' => 'spanish-to-english','description' => '<p>✔️ Above is per page price. Do update number of pages below.<br />
            ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.<br />
            ✔️ Valid Internationally (Visa/immigration office etc).<br />
            ✔️ Duly signed, stamped translation on company&#39;s letterhead along with an Affidavit/Certificate of Translation.<br />
            (For any questions, Whatsapp us)</p>
            
            <p>&nbsp;</p>
            
            <ol>
                <li><strong>Certified translation printed on our company&rsquo;s letterhead, duly certified with our seal and signature.</strong></li>
                <li><strong>An Affidavit/Certificate of Translation containing:</strong></li>
                <li>&bull; confirmation it is an accurate translation of the document</li>
                <li>&bull; the date of the translation</li>
                <li>&bull; the full name and signature of the translator or an official from our company</li>
                <li>&bull; the translator&#39;s or translation company&rsquo;s contact details<br />
                &nbsp;</li>
                <li><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li>
            </ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation spanish to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from Spanish to English and English to spanish from India. Spanish to English certficate translation of Birth, Marriage, Degree Certificate, Divorce etc','meta_keywords' => NULL,'total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-04-24 17:38:23','updated_at' => '2024-04-24 17:38:23','deleted_at' => NULL),
              array('id' => '2','category_id' => NULL,'name' => 'Document Czech sworn translation [Birth Marriage Degree]','language' => 'czechSworn To English','slug' => 'czech-sworn-to-english','description' => '<p>✔️ Above is per page price. Do update number of pages below.<br />
            ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.<br />
            ✔️ Valid Internationally (Visa/immigration office etc).<br />
            ✔️ Duly signed, stamped translation on company&#39;s letterhead along with an Affidavit/Certificate of Translation.<br />
            (For any questions, Whatsapp us)</p>
            
            <ol>
                <li><strong>Certified translation printed on our company&rsquo;s letterhead, duly certified with our seal and signature.</strong></li>
                <li><strong>An Affidavit/Certificate of Translation containing:</strong><br />
                &bull; confirmation it is an accurate translation of the document<br />
                &bull; the date of the translation<br />
                &bull; the full name and signature of the translator or an official from our company<br />
                &bull; the translator&#39;s or translation company&rsquo;s contact details</li>
                <li><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li>
            </ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document Czech sworn translation [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from Czech sworn translation  and English to Czech sworn from India. Czech sworn translation  certficate translation of Birth, Marriage, Degree Certificate, Divorce etc','meta_keywords' => NULL,'total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-04-24 17:41:26','updated_at' => '2024-04-24 17:41:26','deleted_at' => NULL),
              array('id' => '3','category_id' => NULL,'name' => 'Document translation russian to english [Birth Marriage Degree]','language' => 'Russian To English','slug' => 'russian-to-english','description' => '<p>✔️ Above is per page price. Do update number of pages below.<br />
            ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.<br />
            ✔️ Valid Internationally (Visa/immigration office etc).<br />
            ✔️ Duly signed, stamped translation on company&#39;s letterhead along with an Affidavit/Certificate of Translation.<br />
            (For any questions, Whatsapp us)</p>
            
            <p>&nbsp;</p>
            
            <ol>
                <li><strong>Certified translation printed on our company&rsquo;s letterhead, duly certified with our seal and signature.</strong></li>
                <li><strong>An Affidavit/Certificate of Translation containing:</strong><br />
                &bull; confirmation it is an accurate translation of the document<br />
                &bull; the date of the translation<br />
                &bull; the full name and signature of the translator or an official from our company<br />
                &bull; the translator&#39;s or translation company&rsquo;s contact details</li>
                <li><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li>
            </ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation russian  to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  russian to English and English to russian from India. russian to English certficate translation of Birth, Marriage, Degree Certificate, Divorce etc','meta_keywords' => NULL,'total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-04-24 17:46:00','updated_at' => '2024-06-17 22:53:04','deleted_at' => NULL),
              array('id' => '5','category_id' => NULL,'name' => 'Punjabi to English Certified Translation of Birth Certificate, Marriage Certificate and other Documents','language' => 'punjabi-to-english','slug' => 'punjabi-to-english','description' => '<h2>Punjabi to English Certified Translation of Birth Certificate, Marriage Certificate and other Documents</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p>✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p>✔️ Valid Internationally (Visa/immigration office etc).</p><p>✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p>(For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Punjabi%20to%20English%20Certified%20Translation%20of%20Birth%20Certificate,%20Marriage%20Certificate%20and%20other%20Documents" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Punjabi to English Certified Translation of Birth Certificate, Marriage Certificate and other Documents','meta_description' => 'Punjabi to English Certified Translation of Birth Certificate, Marriage Certificate and other Documents','meta_keywords' => 'Punjabi to English Certified Translation of Birth Certificate, Marriage Certificate and other Documents','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:43:05','updated_at' => '2024-06-17 23:49:05','deleted_at' => NULL),
              array('id' => '6','category_id' => NULL,'name' => 'Document translation dutch to english [Birth Marriage Degree]','language' => 'dutch-to-english','slug' => 'dutch-to-english','description' => '<h2>Document translation dutch to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20dutch%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation dutch to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  dutchto English and English to  dutchfrom India.  dutchto English certficate translation of Birth, Marriage, Degree Certificate,  Divorce etc','meta_keywords' => 'Document translation dutch to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:46:55','updated_at' => '2024-06-17 23:45:31','deleted_at' => NULL),
              array('id' => '7','category_id' => NULL,'name' => 'Document translation german to english [Birth Marriage Degree]','language' => 'German to English','slug' => 'german-to-english','description' => '<h2>Document translation german to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20%20german%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation  german to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  german to English and English to  german from India.german to English certficate translation of Birth, Marriage, Degree Certificate,  Divorce etc','meta_keywords' => 'Document translation  german to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:48:15','updated_at' => '2024-06-17 23:45:54','deleted_at' => NULL),
              array('id' => '8','category_id' => NULL,'name' => 'Document translation japanese to english [Birth Marriage Degree]','language' => 'japanese to english','slug' => 'japanese-to-english','description' => '<h2>Document translation japanese to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20japanese%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation japanese to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from japanese to English and English to japanese from India. japanese to English certficate translation of Birth, Marriage, Degree Certificate,  Divorce etc','meta_keywords' => 'Document translation japanese to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:49:25','updated_at' => '2024-06-17 23:46:38','deleted_at' => NULL),
              array('id' => '9','category_id' => NULL,'name' => 'Document translation chinese to english [Birth Marriage Degree]','language' => 'chinese-to-english','slug' => 'chinese-to-english','description' => '<h2>Document translation chinese to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20chinese%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation chinese to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from chinese to English and English to chinese from India. chinese to English certficate translation of Birth, Marriage, Degree Certificate,  Divorce etc','meta_keywords' => 'Document translation chinese to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:50:13','updated_at' => '2024-06-17 23:45:20','deleted_at' => NULL),
              array('id' => '10','category_id' => NULL,'name' => 'Document translation arabic to english [Birth Marriage Degree]','language' => 'arabic-to-english','slug' => 'arabic-to-english','description' => '<h2>Document translation arabic to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20arabic%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation arabic to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  arabic  to English and English to arabic from India. arabic  to English certficate translation of Birth, Marriage, Degree Certificate,  Divorce etc','meta_keywords' => 'Document translation arabic to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:51:15','updated_at' => '2024-06-17 23:45:08','deleted_at' => NULL),
              array('id' => '11','category_id' => NULL,'name' => 'Document translation french to english [Birth Marriage Degree]','language' => 'french-to-english','slug' => 'french-to-english','description' => '<h2>Document translation french to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20french%20%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation french to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  french   to English and English to french  from India. french to English certficate translation of Birth, Marriage, Degree Certificate, Divorce etc','meta_keywords' => 'Document translation french to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:57:07','updated_at' => '2024-06-17 23:45:42','deleted_at' => NULL),
              array('id' => '13','category_id' => NULL,'name' => 'Document translation italian to english [Birth Marriage Degree]','language' => 'italian-to-english','slug' => 'italian-to-english','description' => '<h2>Document translation italian to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20italian%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation italian to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  italian to English and English to italian from India. italian to English certficate translation of Birth, Marriage, Degree Certificate, Divorce etc','meta_keywords' => 'Document translation italian to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 11:59:44','updated_at' => '2024-06-17 23:46:12','deleted_at' => NULL),
              array('id' => '14','category_id' => NULL,'name' => 'Document translation portugal to english [Birth Marriage Degree]','language' => 'portugal-to-english','slug' => 'portugal-to-english','description' => '<h2>Document translation portugal to english [Birth Marriage Degree]</h2><p>✔️ Above is per page price. Do update number of pages below.</p><p> ✔️ Upon completion of translation, we also email scanned copies before shipping and deliver the hard copies across India and abroad.</p><p> ✔️ Valid Internationally (Visa/immigration office etc).</p><p> ✔️ Duly signed, stamped translation on company\'s letterhead along with an Affidavit/Certificate of Translation.</p><p> (For any questions, Whatsapp us)</p><p><a href="https://wa.me/+916353349389&amp;text=Document%20translation%20portugal%20to%20english%20[Birth%20Marriage%20Degree]" rel="noopener noreferrer" target="_blank">Whatsapp Us</a><a href="tel:+916353349389" rel="noopener noreferrer" target="_blank">Call Us</a></p><ol><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Certified translation printed on our company’s letterhead, duly certified with our seal and signature.</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>An Affidavit/Certificate of Translation containing:</strong></li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • confirmation it is an accurate translation of the document</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the date of the translation</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the full name and signature of the translator or an official from our company</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span> • the translator\'s or translation company’s contact details</li><li data-list="ordered"><span class="ql-ui" contenteditable="false"></span><strong>Signed and stamped print-outs of source/original documents to prove/show what we translated.</strong></li></ol>','description_about' => NULL,'image' => 'null','meta_title' => 'Document translation portugal to english [Birth Marriage Degree]','meta_description' => 'Get document certificate translation from  portugal  to English and English to portugal from India. portugal to English certficate translation of Birth, Marriage, Degree Certificate, Divorce etc','meta_keywords' => 'Document translation portugal to english [Birth Marriage Degree]','total_view' => '0','impression' => NULL,'featured_show' => 'False','status' => 'A','canonical' => NULL,'created_by' => '1','updated_by' => NULL,'created_at' => '2024-06-10 12:00:37','updated_at' => '2024-06-17 23:46:56','deleted_at' => NULL)
              );
            }
}
